# Form implementation generated from reading ui file '.\entryPoint.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMessageBox
from mainUI import Ui_MainWindow
from userDataHandler import UserDataHandler
import sys
from functools import partial

class Ui_EntryPoint(object):
    
    def __init__(self):
        self.userData = UserDataHandler()
        self.file_path_users = 'data\\users.json'
    
    
    #-----------------------------------------------------------------------------------------------
    # custom functions Start
       
    def mainUI(self):
        self.mainWindow = QtWidgets.QMainWindow()
        self.ui_main = Ui_MainWindow(self.usernameLineEdit.text())
        self.ui_main.setupUi(self.mainWindow)
        self.mainWindow.show()
       
    def _login(self, currentWindow):
        
        exist = self.userData.checkIfUserExists(self.usernameLineEdit.text())
        
        if exist:
            if self.userData.login(self.usernameLineEdit.text(), self.passwordLineEdit.text()):
                currentWindow.close()
                self.mainUI()
                
            else:
                warningMsg = QMessageBox()
                warningMsg.setWindowTitle("Error")
                warningMsg.setText("password is wrong")
                rep = warningMsg.exec()
        else:
            warningMsg = QMessageBox()
            warningMsg.setWindowTitle("Error")
            warningMsg.setText("Username or password is wrong")
            rep = warningMsg.exec()
            
    def _signup(self):
        exist = self.userData.checkIfUserExists(self.sUsernameLineEdit.text())

        if not exist:
            self.userData.signup(self.sUsernameLineEdit.text(), self.sPasswordLineEdit.text())
            self.tabWidget.setCurrentIndex(0)
            self.tabWidget.setTabEnabled(0, True)
        
        else:
            warningMsg = QMessageBox()
            warningMsg.setWindowTitle("Error")
            warningMsg.setText("User Already exists")
            rep = warningMsg.exec()
            
    def changeTab(self):
        if self.userData.signup_need():
            self.tabWidget.setCurrentIndex(1)
            self.tabWidget.setTabEnabled(0, False)
        elif not self.userData.signup_need():
            self.tabWidget.setCurrentIndex(0)
    
    
    
    # custom functions End
    #-----------------------------------------------------------------------------------------------
    
    
    # SETUP
    
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(549, 592)
        MainWindow.setStyleSheet("background-color: rgb(190, 255, 247);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 551, 592))
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        
        self.login = QtWidgets.QWidget()
        self.login.setObjectName("login")
        
        self.loginLabel = QtWidgets.QLabel(self.login)
        self.loginLabel.setGeometry(QtCore.QRect(-10, 0, 561, 61))
        
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(32)
        
        self.loginLabel.setFont(font)
        self.loginLabel.setStyleSheet("color:rgb(255, 75, 30)")
        self.loginLabel.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.loginLabel.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.loginLabel.setLineWidth(2)
        self.loginLabel.setMidLineWidth(2)
        self.loginLabel.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.loginLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.loginLabel.setObjectName("loginLabel")
        
        self.label = QtWidgets.QLabel(self.login)
        self.label.setGeometry(QtCore.QRect(120, 110, 111, 51))
        
        font = QtGui.QFont()
        font.setPointSize(15)
        
        self.label.setFont(font)
        self.label.setStyleSheet("color:rgb(255, 34, 34)")
        self.label.setFrameShape(QtWidgets.QFrame.Shape.Panel)
        self.label.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.label.setLineWidth(3)
        self.label.setMidLineWidth(0)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        
        self.usernameLineEdit = QtWidgets.QLineEdit(self.login)
        self.usernameLineEdit.setGeometry(QtCore.QRect(290, 190, 131, 31))
        self.usernameLineEdit.setObjectName("usernameLineEdit")
        
        self.label_2 = QtWidgets.QLabel(self.login)
        self.label_2.setGeometry(QtCore.QRect(120, 270, 111, 51))
        
        font = QtGui.QFont()
        font.setPointSize(15)
        
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:rgb(255, 34, 34)")
        self.label_2.setFrameShape(QtWidgets.QFrame.Shape.Panel)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.label_2.setLineWidth(3)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        
        self.passwordLineEdit = QtWidgets.QLineEdit(self.login)
        self.passwordLineEdit.setGeometry(QtCore.QRect(290, 350, 131, 31))
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        
        self.loginButton = QtWidgets.QPushButton(self.login)
        self.loginButton.setGeometry(QtCore.QRect(180, 450, 171, 41))
        
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        
        self.loginButton.setFont(font)
        self.loginButton.setStyleSheet("background-color: rgb(36, 255, 24);")
        self.loginButton.setObjectName("loginButton")
        
        self.tabWidget.addTab(self.login, "")
        
        self.signup = QtWidgets.QWidget()
        self.signup.setObjectName("signup")
        
        self.label_3 = QtWidgets.QLabel(self.signup)
        self.label_3.setGeometry(QtCore.QRect(-10, 0, 561, 61))
        
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(32)
        
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:rgb(255, 75, 30)")
        self.label_3.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.label_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.label_3.setLineWidth(2)
        self.label_3.setMidLineWidth(2)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        
        self.label_4 = QtWidgets.QLabel(self.signup)
        self.label_4.setGeometry(QtCore.QRect(120, 110, 111, 51))
        
        font = QtGui.QFont()
        font.setPointSize(15)
        
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:rgb(255, 34, 34)")
        self.label_4.setFrameShape(QtWidgets.QFrame.Shape.Panel)
        self.label_4.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.label_4.setLineWidth(3)
        self.label_4.setMidLineWidth(0)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        
        self.label_5 = QtWidgets.QLabel(self.signup)
        self.label_5.setGeometry(QtCore.QRect(120, 270, 111, 51))
        
        font = QtGui.QFont()
        font.setPointSize(15)
        
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:rgb(255, 34, 34)")
        self.label_5.setFrameShape(QtWidgets.QFrame.Shape.Panel)
        self.label_5.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.label_5.setLineWidth(3)
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")
        
        self.sUsernameLineEdit = QtWidgets.QLineEdit(self.signup)
        self.sUsernameLineEdit.setGeometry(QtCore.QRect(290, 190, 131, 31))
        self.sUsernameLineEdit.setObjectName("sUsernameLineEdit")
        
        self.sPasswordLineEdit = QtWidgets.QLineEdit(self.signup)
        self.sPasswordLineEdit.setGeometry(QtCore.QRect(290, 350, 131, 31))
        self.sPasswordLineEdit.setObjectName("sPasswordLineEdit")
        
        self.signupButton = QtWidgets.QPushButton(self.signup)
        self.signupButton.setGeometry(QtCore.QRect(180, 450, 171, 41))
        
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        
        self.signupButton.setFont(font)
        self.signupButton.setStyleSheet("background-color: rgb(36, 255, 24);")
        self.signupButton.setObjectName("signupButton")
        
        self.tabWidget.addTab(self.signup, "")
        
        MainWindow.setCentralWidget(self.centralwidget)
        
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 549, 22))
        self.menubar.setObjectName("menubar")
        
        MainWindow.setMenuBar(self.menubar)
        
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.changeTab()
        
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        ####Button signals
        self.loginButton.clicked.connect(partial(self._login, MainWindow))
        self.signupButton.clicked.connect(self._signup)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.loginLabel.setText(_translate("MainWindow", "Login"))
        self.label.setText(_translate("MainWindow", "Username"))
        self.label_2.setText(_translate("MainWindow", "Password"))
        self.loginButton.setText(_translate("MainWindow", "Login"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.login), _translate("MainWindow", "Login"))
        self.label_3.setText(_translate("MainWindow", "Sign Up"))
        self.label_4.setText(_translate("MainWindow", "Username"))
        self.label_5.setText(_translate("MainWindow", "Password"))
        self.signupButton.setText(_translate("MainWindow", "Sign Up"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.signup), _translate("MainWindow", "Sign Up"))


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_EntryPoint()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
