# Form implementation generated from reading ui file 'c:\Users\DELL\OneDrive\Desktop\python codes\Cash Bank\VisualizeData.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(204, 292)
        self.datTable = QtWidgets.QTableWidget(Form)
        self.datTable.setGeometry(QtCore.QRect(-5, 0, 231, 301))
        self.datTable.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.datTable.setObjectName("datTable")
        self.datTable.setColumnCount(1)
        self.datTable.setRowCount(9)
        item = QtWidgets.QTableWidgetItem()
        self.datTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.datTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.datTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.datTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.datTable.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.datTable.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.datTable.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.datTable.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.datTable.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.datTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.datTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.datTable.setItem(1, 0, item)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        item = self.datTable.verticalHeaderItem(0)
        item.setText(_translate("Form", "Date"))
        item = self.datTable.verticalHeaderItem(1)
        item.setText(_translate("Form", "Spent"))
        item = self.datTable.verticalHeaderItem(2)
        item.setText(_translate("Form", "Gained"))
        item = self.datTable.verticalHeaderItem(3)
        item.setText(_translate("Form", "Saved today"))
        item = self.datTable.verticalHeaderItem(4)
        item.setText(_translate("Form", "Withdrawed"))
        item = self.datTable.verticalHeaderItem(5)
        item.setText(_translate("Form", "Total savings"))
        item = self.datTable.verticalHeaderItem(6)
        item.setText(_translate("Form", "Total"))
        item = self.datTable.verticalHeaderItem(7)
        item.setText(_translate("Form", "Total left to spend"))
        item = self.datTable.verticalHeaderItem(8)
        item.setText(_translate("Form", "Total spent"))
        item = self.datTable.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Value"))
        __sortingEnabled = self.datTable.isSortingEnabled()
        self.datTable.setSortingEnabled(False)
        item = self.datTable.item(0, 0)
        item.setText(_translate("Form", "1"))
        item = self.datTable.item(1, 0)
        item.setText(_translate("Form", "2"))
        self.datTable.setSortingEnabled(__sortingEnabled)
